import:
  - logstash-plugins/.ci:travis/defaults.yml@1.x
  - logstash-plugins/.ci:travis/exec.yml@1.x

env:
  jobs:
    # lock on version 8.x because use Ruby 2.6.0 available from 8.4.0
    - ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk21.env
    - SNAPSHOT=true ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk21.env
