import:
  - logstash-plugins/.ci:travis/defaults.yml@1.x
  - logstash-plugins/.ci:travis/exec.yml@1.x

env:
  jobs:
    # lock on version 8.x because use API available from 8.4.0
    - ELASTIC_STACK_VERSION=8.x
    - SNAPSHOT=true ELASTIC_STACK_VERSION=8.x
